# -*- coding: utf-8 -*-
"""datetime_transformacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q25k-2WyFp4Wl-uuYsSVVhttzqxFQFYi
"""

import pandas as pd
import datetime as dt

#lendo e conhecendo os arquivos
dt_data = pd.read_json('/content/moveis_disponiveis.json')
dt_data.head()

dt_data.info()

#transformando a coluna para datetime
pd.to_datetime(dt_data['data'])

#substituindo os dados
dt_data['data'] = pd.to_datetime(dt_data['data'])

dt_data.info()

#formatando o formato:
#dados['Data de venda'] = pd.to_datetime(dados['Data de venda'], format='%d/%m/%Y')

dt_data.head()

dt_data['data'].dt.strftime('%Y-%m') #formatando o tempo, excluindo dia

#agrupando as vagas disponíveis pelos meses
dt_data.groupby(dt_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()

#atribuindo o resultado a uma var
subset = dt_data.groupby(dt_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()
subset

# importamos a biblioteca numpy
import numpy as np

# utilizamos o método fillna para preencher os elementos vazios por '0.0'
# definimos o parâmetro de inplace para True para substituir no DataFrame
dt_data['preco'].fillna('0.0', inplace = True)

# apagamos o $ e as vírgulas com apply lambda
dt_data['preco'] = dt_data['preco'].apply(lambda x: x.replace('$', '').replace(',',''))

# transformamos os tipos de dados para float64
dt_data['preco'] = dt_data['preco'].astype(np.float64)

# observamos o resultado final
dt_data